Add sitemap and gdpr plugin, and add plugin tasks
monsieurbiz/sylius-setup pull request #13
Opened 2023-09-05 13:03 UTC by delyriand

2023-09-05 17:13 UTC, jacquesbh requested changes

2023-09-05 17:13 UTC, jacquesbh commented on castor.php
> +        run('rm -rf themes-examples');
I'm not a huge fan of this.

We don't propose a way to install the custom theme automatically, so removing it is kind of sad.

2023-09-05 17:13 UTC, jacquesbh commented on castor/sylius.php
> +            io()->info('Follow the installation guide: https://github.com/stefandoorn/sitemap-plugin#installation');
A while loop is missing here to be sure that the developer has done the installation correcly.

2023-09-05 17:13 UTC, jacquesbh commented on castor/sylius.php
> +            io()->info('Follow the installation guide: https://github.com/synolia/SyliusGDPRPlugin#installation');
Same here, maybe we need a loop to block the user on going forward before it's really installed?

2023-09-06 07:03 UTC, delyriand commented on castor.php
> +        run('rm -rf themes-examples');
if you want ;)

2023-09-06 12:34 UTC, jacquesbh approved these changes

2023-09-06 12:35 UTC, merged