Add admin order creation, invoicing and refund plugins
monsieurbiz/sylius-setup pull request #26
Opened 2024-01-23 19:56 UTC by delyriand

2024-01-23 21:47 UTC, jacquesbh requested changes

2024-01-23 21:47 UTC, jacquesbh commented on castor/sylius.php
> +            io()->info('Follow the installation guide:https://github.com/Sylius/AdminOrderCreationPlugin#installation');
```suggestion
            io()->info('Follow the installation guide: https://github.com/Sylius/AdminOrderCreationPlugin#installation');
```

2024-01-24 08:25 UTC, etienne-monsieurbiz approved these changes

2024-01-24 12:48 UTC, maximehuran approved these changes

2024-01-25 08:23 UTC, lanfisis approved these changes

2024-01-31 08:27 UTC, merged