Few fixes
monsieurbiz/sylius-setup pull request #38
Opened 2024-09-16 11:12 UTC by jacquesbh

- feat: Use Context objects instead of deprecated parameters
- feat: Better way to get the default value of the repo's name

2024-09-16 11:33 UTC, delyriand commented on castor.php
> +    run('symfony composer config scripts.phpmd "phpmd src/,plugins/ ansi phpmd.xml --exclude src/Migrations"', workingDirectory: 'apps/sylius/');
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❔ question:** why not use `context: $composerContext` for these two commands as for the others?‏

2024-09-17 06:49 UTC, delyriand requested changes

2024-09-17 06:49 UTC, delyriand commented on castor.php
> +    run('symfony composer update', context: $composerContext);
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❔ question:** you go from a false timeout to DEFAULT_TIMEOUT_COMPOSER_PROCESS with this context. won't this present problems during the run?‏

2024-09-17 06:49 UTC, delyriand commented on castor.php
> +}
<!-- Chores are simple tasks that must be done before the subject can be “officially” accepted. Usually, these comments reference some common process. Try to leave a link to the process description so that the reader knows how to resolve the chore.  -->
**💣 chore:** remove the test task‏

2024-09-17 07:55 UTC, jacquesbh commented on castor.php
> +    run('symfony composer update', context: $composerContext);
Non, I don't think so. It's composer anyway, we need this step.

2024-09-17 07:57 UTC, jacquesbh commented on castor.php
> +}
Arf. I was being careful not to include it, then after your first review I made a mistake and did include it… Damn me.

2024-09-17 08:03 UTC, delyriand approved these changes

2024-09-17 14:47 UTC, merged