fix(phpstan): Fix deprecated config and lower the level from max to 8
monsieurbiz/sylius-setup pull request #39
Opened 2024-09-24 10:18 UTC by welcoMattic

- Lower level from `max` to `8`. As explained [here](https://phpstan.org/user-guide/rule-levels) (and as [PHPStan itself](https://github.com/phpstan/phpstan-src/blob/2.0.x/build/phpstan.neon#L14) doesn't use the `max` level), the `max` (== `9`) level is only about being strict with `mixed` type, which can be annoying when we need to extend classes from dependencies.

- Fixed deprecated config to avoid those warnings (commented by default to avoid instant failing PHPStan analyse on a fresh setup)

```
⚠️  You're using a deprecated config option checkMissingIterableValueType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing array typehints.

If you want to continue ignoring missing typehints from arrays,
add missingType.iterableValue error identifier to your ignoreErrors:

parameters:
	ignoreErrors:
		-
			identifier: missingType.iterableValue

⚠️  You're using a deprecated config option checkGenericClassInNonGenericObjectType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing generic typehints.

If you want to continue ignoring missing typehints from generics,
add missingType.generics error identifier to your ignoreErrors:

parameters:
	ignoreErrors:
		-
			identifier: missingType.generics
```

2024-09-24 10:27 UTC, jacquesbh requested changes

2024-09-24 10:27 UTC, jacquesbh commented on dist/sylius/phpstan.neon
> +    level: 8
We had the max level until now so I suggest we keep it that way.

WDYT?

2024-09-24 10:27 UTC, jacquesbh commented on resources/makefiles/testing.mk
> -	${PHPSTAN} analyse -c phpstan.neon src/ plugins/
Why don't we need the paths anymore?

2024-09-25 06:54 UTC, maximehuran commented on dist/sylius/phpstan.neon
> +    level: 8
We had this discussion together and in projects and plugin, we use level 8 to avoid a lot of issues with mixed vars.
PHP Stan itself use the level 8 in their tools.

2024-09-25 07:01 UTC, delyriand commented on resources/makefiles/testing.mk
> -	${PHPSTAN} analyse -c phpstan.neon src/ plugins/
Because paths are defined in the neon file

2024-09-25 07:03 UTC, delyriand approved these changes

2024-09-25 14:32 UTC, maximehuran approved these changes

2024-09-25 15:48 UTC, etienne-monsieurbiz approved these changes

2024-10-09 08:48 UTC, jacquesbh approved these changes

2024-10-09 08:48 UTC, merged